name: Deploy Ingress Controller

on:
  workflow_dispatch:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  deploy-ingress-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create kubeconfig file
        run: echo "$KUBE_CONFIG" > kubeconfig.yaml

      
