name: Kubectl Deploy Ingress Controller

on:
  push:
    branches:
      - development

jobs:
  deploy-ingress-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' 

      - name: Authenticate with K8s Cluster
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        run: |
          mkdir -p $(dirname $KUBECONFIG)
          echo "" > $KUBECONFIG
          kubectl config set-cluster Flash_Cluster --server=https://F173F9DC1AEA27CA9C66A37BEE1DB28E.gr7.us-east-1.eks.amazonaws.com
          kubectl config set-credentials Flash_Cluster-credentials --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context Flash_Cluster-context --cluster=Flash_Cluster --user=Flash_Cluster-credentials
          kubectl config use-context Flash_Cluster-context
          touch kubeconfig.yaml  

      - name: Create kubeconfig file
        run: |
          echo "$KUBE_CONFIG" > kubeconfig.yaml

      - name: Apply Ingress Controller
        run: |
          kubectl apply -f ingress-controller.yaml --kubeconfig=kubeconfig.yaml --validate=false
