name: Create kubeconfig

on:
  push:
    branches:
      - development

jobs:
  deploy-ingress-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create kubeconfig file
        run: echo "$KUBE_CONFIG" > kubeconfig.yaml

      - name: Decode CA certificate data
        run: echo "${{ secrets.CA_CERT_DATA }}" | base64 -d > ca.crt 
         

      - name: Apply Ingress Controller
        run: |
          kubectl apply -f ingress-controller.yaml --kubeconfig=kubeconfig.yaml --validate=false
