name: Kubectl Deploy Ingress Controller

on:
  push:
    branches:
      - development

jobs:
  deploy-ingress-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install kubectl
        run: |
         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         chmod +x ./kubectl
         sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install aws-iam-authenticator
        run: |
         curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/aws-iam-authenticator
         chmod +x ./aws-iam-authenticator
         sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator


      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' 

      - name: Authenticate with K8s Cluster
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        run: |
          mkdir -p $(dirname $KUBECONFIG)
          kubectl config set-cluster Flash_Cluster --server=https://F173F9DC1AEA27CA9C66A37BEE1DB28E.gr7.us-east-1.eks.amazonaws.com --insecure-skip-tls-verify=true
          kubectl config set-credentials Flash_Cluster_EKS-credentials --token=k8s-aws-v1.aHR0cHM6Ly9zdHMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vP0FjdGlvbj1HZXRDYWxsZXJJZGVudGl0eSZWZXJzaW9uPTIwMTEtMDYtMTUmWC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBMlhaM1RBQzRWRVlUT1lXSSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGc3RzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDY1MjEzWiZYLUFtei1FeHBpcmVzPTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCUzQngtazhzLWF3cy1pZCZYLUFtei1TaWduYXR1cmU9ODBmMTA5MTcwYTc2ZWRjZDdiMjQzZDhlMGJjNGEzZThlZjBkYmI4MTgzZmI1MDc1ZWQ4Njg2ODI4OTcyNjJhZg
          kubectl config set-context Flash_Cluster-context --cluster=Flash_Cluster --user=Flash_Cluster-credentials
          kubectl config use-context Flash_Cluster-context

      - name: Debug KUBECONFIG
        run: cat ${{ github.workspace }}/.kube/config

      - name: Apply Kubernetes manifests
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config
        run: |
          kubectl apply -f ingress-controller.yaml --validate=false
